version: "3"
services:
  frontend:
    build: ./frontend
    image: frontend
    environment:
      PORT: 8080
      AUTH_API_ADDRESS: http://auth-api:8081
      TODOS_API_ADDRESS: http://todos-api:8082
      ZIPKIN_URL: http://docker.for.mac.localhost:9411/api/v2/spans
    ports:
      - 8080:8080
    depends_on:
      - auth-api
      - todos-api
      - users-api

  auth-api:
    build: ./auth-api
    image: auth-api
    environment:
      AUTH_API_PORT: 8081
      JWT_SECRET: myfancysecret
      USERS_API_ADDRESS: http://users-api:8083
      ZIPKIN_URL: http://docker.for.mac.localhost:9411/api/v2/spans
    depends_on:
      - users-api

  todos-api:
    build: ./todos-api
    image: todos-api
    environment:
      TODO_API_PORT: 8082
      JWT_SECRET: myfancysecret
      REDIS_HOST: redis-queue
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ZIPKIN_URL: http://docker.for.mac.localhost:9411/api/v2/spans
    depends_on:
      - redis-queue

  users-api:
    build: ./users-api
    image: users-api
    environment:
     SERVER_PORT: 8083
     JWT_SECRET: myfancysecret
     SPRING_ZIPKIN_BASE_URL: http://docker.for.mac.localhost:9411
     
  log-message-processor:
    build: ./log-message-processor
    image: log-message-processor
    environment:
      REDIS_HOST: redis-queue
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ZIPKIN_URL: http://docker.for.mac.localhost:9411/api/v1/spans
    depends_on:
      - redis-queue

  redis-queue:
    image: redis